import mongoose from "mongoose";
const availableSkills = [
    "Java",
    "Python",
    "JavaScript",
    "TypeScript",
    "C",
    "C++",
    "Go",
    "Rust",
    "PHP",
    "Kotlin",
    "Swift",
    "HTML",
    "CSS",
    "SASS",
    "Tailwind",
    "Bootstrap",
    "React",
    "Next.js",
    "Vue",
    "Angular",
    "Node.js",
    "Express",
    "NestJS",
    "Spring Boot",
    "Django",
    "Flask",
    "FastAPI",
    "MongoDB",
    "MySQL",
    "PostgreSQL",
    "Redis",
    "SQLite",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "GCP",
    "Nginx",
    "Linux",
    "REST API",
    "GraphQL",
    "Socket.IO",
    "JWT",
    "OAuth",
    "Git",
    "GitHub",
    "CI/CD",
    "System Design",
    "DSA",
    "Microservices",
    "Testing",
    "Performance",
];
const UserSchema = new mongoose.Schema({
  username: { type: String, required: true },
  email: { type: String, required: true, unique: true },
  bio: { type: String, default: "" },
  skills: { type: [String],enum : availableSkills, default: [] },
  password: { type: String, required: true },
  image: { type: String, default: "" },
});
export { availableSkills };
export const User =
    mongoose.models.User || mongoose.model("User", UserSchema);
